version: '3'

services:
  issue-web:
    container_name: issue-web
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    links:
      - issue-app
    volumes:
      - ./:/var/www/:rw
      - ./docker/nginx/issue.local:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80
    networks:
      issue-network:
        ipv4_address: 130.10.0.2
    restart: unless-stopped

  issue-app:
    container_name: issue-app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    links:
      - issue-db
    volumes:
      - ./:/var/www/:rw
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /var/www/
    expose:
      - 9000
    networks:
      issue-network:
        ipv4_address: 130.10.0.3
    restart: unless-stopped

  issue-db:
    container_name: issue-db
    image: mysql:latest
    expose:
      - 3306
    volumes:
      - issue-mysql:/var/lib/mysql/:rw
      - ./docker/mysql/mysql-entrypoint-init.sql:/docker-entrypoint-initdb.d/mysql-entrypoint-init.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=issueroot
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=Europe/Kiev
    networks:
      issue-network:
        ipv4_address: 130.10.0.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

networks:
  issue-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 130.10.0.0/24
    driver_opts:
      com.docker.network.bridge.name: br_issue

volumes:
  issue-mysql:
